tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/bundle"
tap "homebrew/core"
tap "universal-ctags/universal-ctags"
brew "readline"
brew "bash"
brew "coreutils"
brew "dep"
brew "direnv"
brew "git"
brew "docker"
brew "libyaml"
brew "docker-compose"
brew "freetype"
brew "gnupg"
brew "go"
brew "htop"
brew "ipcalc"
brew "jq"
brew "openssl"
brew "lastpass-cli"
brew "lua"
brew "mas"
brew "minio-mc"
brew "python3"
brew "protobuf"
brew "reattach-to-user-namespace"
brew "s3cmd"
brew "shellcheck"
brew "the_silver_searcher"
brew "tig"
brew "tmate"
brew "tmux"
brew "tree"
brew "vim", args: ["with-lua"]
brew "watch"
brew "wget"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]
cask "docker"
cask "dropbox"
cask "flycut"
cask "font-inconsolata"
cask "google-chrome"
cask "iterm2"
cask "iina"
cask "rectangle"
cask "sublime-text"
cask "telegram-desktop"
cask "transmission"
cask "yujitach-menumeters"
mas "Microsoft To Do", id: 1274495053
mas "The Unarchiver", id: 425424353
mas "WeChat", id: 836500024
